image:
  file: .gitpod.Dockerfile

tasks:
- before: export ROOT_URL=$(gp url 3000)
  init: meteor npm install
  command: meteor npm start

ports:
- port: 3000
  onOpen: open-browser
# - port: 3001 # mongo db
#   onOpen: ignore
